#encoding: utf-8

namespace :create_brands do
  desc "TODO"
  task create: :environment do
    Brand.create(:name => "AleSmith Brewing Company")
    Brand.create(:name => "The Lost Abbey")
    Brand.create(:name => "Alpine Beer Company")
    Brand.create(:name => "Societe Brewing Co.")
    Brand.create(:name => "Modern Times Beer")
    Brand.create(:name => "Port Brewing")
    Brand.create(:name => "Toolbox Brewing Company")
    Brand.create(:name => "Barrel Harbor Brewing")
    Brand.create(:name => "Council Brewing Company")
    Brand.create(:name => "Stone Brewing Co.")
    Brand.create(:name => "Bagby Beer Company")
    Brand.create(:name => "Green Flash Brewing Co.")
    Brand.create(:name => "Ballast Point Brewing Company")
    Brand.create(:name => "Pizza Port Solana Beach")
    Brand.create(:name => "Pizza Port Carlsbad")
    Brand.create(:name => "Pizza Port Ocean Beach")
    Brand.create(:name => "Pizza Port Bressi Ranch")
    Brand.create(:name => "Intergalactic Brewing Co.")
    Brand.create(:name => "Monkey Paw Pub & Brewery")
    Brand.create(:name => "Benchmark Brewing")
    Brand.create(:name => "Rip Current Brewing")
    Brand.create(:name => "Belching Beaver Brewery")
    Brand.create(:name => "Latitude 33° Brewing Company")
    Brand.create(:name => "Mike Hess Brewing - Miramar")
    Brand.create(:name => "The Beer Company")
    Brand.create(:name => "Blind Lady Ale House & Automatic Brewing Co.")
    Brand.create(:name => "Coronado Brewing Company")
    Brand.create(:name => "Acoustic Ales Brewing Experiment")
    Brand.create(:name => "Rock Bottom Restaurant and Brewery")
    Brand.create(:name => "Urbn St. Brewing Co.")
    Brand.create(:name => "Back Street Brewery")
    Brand.create(:name => "Legacy Brewing Co.")
    Brand.create(:name => "Culture Brewing Co.")
    Brand.create(:name => "Amplified Ale Works")
    Brand.create(:name => "Offbeat Brewing Company")
    Brand.create(:name => "Prohibition Brewing Company")
    Brand.create(:name => "2kids Brewing Company")
    Brand.create(:name => "Iron Fist Brewing Company")
    Brand.create(:name => "San Diego Brewing Co.")
    Brand.create(:name => "Mother Earth Brew Co.")
    Brand.create(:name => "Pacific Brewing Company")
    Brand.create(:name => "Butcher's Brewing")
    Brand.create(:name => "El Cajon Brewing Company")
    Brand.create(:name => "Rough Draft Brewing Company")
    Brand.create(:name => "Mission Brewery")
    Brand.create(:name => "ChuckAlek Independent Brewers")
    Brand.create(:name => "Aztec Brewing Company")
    Brand.create(:name => "BNS Brewing & Distilling Co.")
    Brand.create(:name => "Saint Archer Brewing Co.")
    Brand.create(:name => "Groundswell Brewing Company")
    Brand.create(:name => "Lightning Brewer")
  end
end